name: Update podcast.xml
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Call Podcast_Generator
        uses: DjTamotsu/Podcast_Generator@main
